export const MovieDetailsActionTypes = {
  FETCH_MOVIE_DETAILS_REQUEST : 'FETCH_MOVIE_DETAILS_REQUEST',
  FETCH_MOVIE_DETAILS_SUCCES : 'FETCH_MOVIE_DETAILS_SUCCES',
  FETCH_MOVIE_DETAILS_FAILURE : 'FETCH_MOVIE_DETAILS_FAILURE',
}